create a basic input component and add to accordion
Laboratorio-de-Des-Software/Sambook_FE pull request #12
Opened 2023-11-13 23:47 UTC by pedrolpaes

2023-11-14 03:37 UTC, rborges98 commented on src/components/Input/index.tsx
> +export { default } from './Index'
from './Input'

2023-11-14 03:40 UTC, rborges98 commented on src/components/Input/Input.tsx
> +const Input = ({ label, rows, placeholder = "" }: InputProps) => {
como esse eh um input de textarea, bota no nome do componente isso, por que vamos ter outros tipos de input tambem

2023-11-14 03:41 UTC, rborges98 commented on src/components/AccordionLayout/Accordion.tsx
> +import Input from  '../Input/Input'
'../Input'

2023-11-14 03:41 UTC, rborges98 requested changes

2023-11-14 03:41 UTC, rborges98 commented on src/components/Input/Input.tsx
> +const Input = ({ label, rows, placeholder = "" }: InputProps) => {
como esse eh um input de textarea, bota no nome do componente isso, por que vamos ter outros tipos de input tambem

2023-11-15 22:23 UTC, rborges98 approved these changes

2023-11-16 12:25 UTC, ImGlic approved these changes

2023-11-16 12:25 UTC, merged